# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-13 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
