# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-13 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200313_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(13, 'Shareable'), (14, 'Returnable'), (15, 'Permanent')], default=14),
        ),
    ]
