# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200313_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteditem',
            name='requested_to',
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='requested_to',
            field=models.PositiveSmallIntegerField(choices=[(16, 'Admin_Manager'), (17, 'User')], default=16),
        ),
    ]
