# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20200313_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteditem',
            name='requested_to',
        ),
    ]
