# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_remove_requesteditem_requested_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_requests', to='item.RequestedItem'),
        ),
    ]
