# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-24 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200314_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approveditem',
            name='approved_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_items', to='item.Item'),
        ),
        migrations.AlterField(
            model_name='approveditem',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_request', to='item.RequestedItem'),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests', to='item.ItemGroup'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Pending'), (8, 'Approved'), (9, 'Cancelled'), (18, 'Rejected')], default=7),
        ),
    ]
