# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200324_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveditem',
            name='approved_duration',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='requested_duration',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
