# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20200325_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approveditem',
            name='approved_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='requested_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
