# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-27 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20200325_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveditem',
            name='current_status_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='current_status_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 27, 7, 14, 33, 441327, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
