# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-27 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_itemhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='approved_duration',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='itemhistory',
            name='requested_duration',
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='approved_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.ApprovedItem'),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Pending'), (11, 'Acknowledged'), (12, 'Returned')], default=10),
        ),
    ]
