# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-27 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20200327_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemhistory',
            old_name='approved_item',
            new_name='approved',
        ),
    ]
