# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-03-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Admin'), (5, 'Manager'), (6, 'User')], default=6),
        ),
    ]
